# fly.toml app configuration file generated for anishare_admin

app = 'anishare-admin'
primary_region = 'nrt'  # Tokyo region for better performance in Japan

[build]

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[deploy]
  release_command = 'echo "Deployment completed"'
